/**
 * @fileoverview Bundled ICS International Chronostratigraphic time-scale snapshot.
 *
 * Generated once from PBDB `/intervals/list?scale_id=1` (the ICS international
 * scale) and checked in so {@link IntervalIndex} resolves named intervals ↔ Ma
 * with no network call. Regenerate on ICS revision; bump `ICS_VERSION`.
 *
 * Boundaries: `max_ma` is the older (bottom, PBDB `b_age`) boundary, `min_ma` the
 * younger (top, PBDB `t_age`). `level` is PBDB's interval `type`.
 *
 * Source: https://paleobiodb.org/data1.2/intervals/list?scale_id=1
 * @module services/intervals/time-scale-data
 */

import type { Interval } from '../pbdb/types.js';

/** ICS chart version this snapshot reflects. Surfaced as `snapshot_version`. */
export const ICS_VERSION = '2023/09';

/** Date this snapshot was generated (ISO 8601). */
export const SNAPSHOT_GENERATED = '2026-06-23';

/** The bundled geologic intervals (ICS international scale). */
export const ICS_INTERVALS: readonly Interval[] = [
  {
    interval_no: 751,
    name: 'Phanerozoic',
    level: 'eon',
    max_ma: 538.8,
    min_ma: 0,
    color: '#9AD9DD',
  },
  {
    interval_no: 1,
    name: 'Cenozoic',
    level: 'era',
    max_ma: 66,
    min_ma: 0,
    parent_no: 751,
    color: '#F2F91D',
    abbrev: 'Cz',
  },
  {
    interval_no: 12,
    name: 'Quaternary',
    level: 'period',
    max_ma: 2.58,
    min_ma: 0,
    parent_no: 1,
    color: '#F9F97F',
    abbrev: 'Q',
  },
  {
    interval_no: 32,
    name: 'Holocene',
    level: 'epoch',
    max_ma: 0.0117,
    min_ma: 0,
    parent_no: 12,
    color: '#FEF2E0',
  },
  {
    interval_no: 1200,
    name: 'Meghalayan',
    level: 'age',
    max_ma: 0.0042,
    min_ma: 0,
    parent_no: 32,
    color: '#FEF2E0',
  },
  {
    interval_no: 1201,
    name: 'Northgrippian',
    level: 'age',
    max_ma: 0.0082,
    min_ma: 0.0042,
    parent_no: 32,
    color: '#FEF2E0',
  },
  {
    interval_no: 1202,
    name: 'Greenlandian',
    level: 'age',
    max_ma: 0.0117,
    min_ma: 0.0082,
    parent_no: 32,
    color: '#FEF2E0',
  },
  {
    interval_no: 33,
    name: 'Pleistocene',
    level: 'epoch',
    max_ma: 2.58,
    min_ma: 0.0117,
    parent_no: 12,
    color: '#FFF2AE',
    abbrev: 'Ple',
  },
  {
    interval_no: 922,
    name: 'Late Pleistocene',
    level: 'age',
    max_ma: 0.129,
    min_ma: 0.0117,
    parent_no: 33,
    color: '#FFF2C7',
  },
  {
    interval_no: 1203,
    name: 'Chibanian',
    level: 'age',
    max_ma: 0.774,
    min_ma: 0.129,
    parent_no: 33,
    color: '#FFF2C7',
  },
  {
    interval_no: 740,
    name: 'Calabrian',
    level: 'age',
    max_ma: 1.8,
    min_ma: 0.774,
    parent_no: 33,
    color: '#FFF2C7',
  },
  {
    interval_no: 741,
    name: 'Gelasian',
    level: 'age',
    max_ma: 2.58,
    min_ma: 1.8,
    parent_no: 33,
    color: '#FFEDB3',
  },
  {
    interval_no: 25,
    name: 'Neogene',
    level: 'period',
    max_ma: 23.04,
    min_ma: 2.58,
    parent_no: 1,
    color: '#FFE619',
    abbrev: 'Ng',
  },
  {
    interval_no: 34,
    name: 'Pliocene',
    level: 'epoch',
    max_ma: 5.333,
    min_ma: 2.58,
    parent_no: 25,
    color: '#FFFF99',
    abbrev: 'Pli',
  },
  {
    interval_no: 96,
    name: 'Piacenzian',
    level: 'age',
    max_ma: 3.6,
    min_ma: 2.58,
    parent_no: 34,
    color: '#FFFFBF',
  },
  {
    interval_no: 97,
    name: 'Zanclean',
    level: 'age',
    max_ma: 5.333,
    min_ma: 3.6,
    parent_no: 34,
    color: '#FFFFB3',
  },
  {
    interval_no: 35,
    name: 'Miocene',
    level: 'epoch',
    max_ma: 23.04,
    min_ma: 5.333,
    parent_no: 25,
    color: '#FFFF00',
    abbrev: 'Mio',
  },
  {
    interval_no: 98,
    name: 'Messinian',
    level: 'age',
    max_ma: 7.246,
    min_ma: 5.333,
    parent_no: 35,
    color: '#FFFF73',
  },
  {
    interval_no: 99,
    name: 'Tortonian',
    level: 'age',
    max_ma: 11.63,
    min_ma: 7.246,
    parent_no: 35,
    color: '#FFFF66',
  },
  {
    interval_no: 100,
    name: 'Serravallian',
    level: 'age',
    max_ma: 13.82,
    min_ma: 11.63,
    parent_no: 35,
    color: '#FFFF59',
  },
  {
    interval_no: 101,
    name: 'Langhian',
    level: 'age',
    max_ma: 15.98,
    min_ma: 13.82,
    parent_no: 35,
    color: '#FFFF4D',
  },
  {
    interval_no: 102,
    name: 'Burdigalian',
    level: 'age',
    max_ma: 20.45,
    min_ma: 15.98,
    parent_no: 35,
    color: '#FFFF41',
  },
  {
    interval_no: 103,
    name: 'Aquitanian',
    level: 'age',
    max_ma: 23.04,
    min_ma: 20.45,
    parent_no: 35,
    color: '#FFFF33',
  },
  {
    interval_no: 26,
    name: 'Paleogene',
    level: 'period',
    max_ma: 66,
    min_ma: 23.04,
    parent_no: 1,
    color: '#FD9A52',
    abbrev: 'Pg',
  },
  {
    interval_no: 36,
    name: 'Oligocene',
    level: 'epoch',
    max_ma: 33.9,
    min_ma: 23.04,
    parent_no: 26,
    color: '#FDC07A',
    abbrev: 'Ol',
  },
  {
    interval_no: 104,
    name: 'Chattian',
    level: 'age',
    max_ma: 27.3,
    min_ma: 23.04,
    parent_no: 36,
    color: '#FEE6AA',
  },
  {
    interval_no: 105,
    name: 'Rupelian',
    level: 'age',
    max_ma: 33.9,
    min_ma: 27.3,
    parent_no: 36,
    color: '#FED99A',
  },
  {
    interval_no: 37,
    name: 'Eocene',
    level: 'epoch',
    max_ma: 56,
    min_ma: 33.9,
    parent_no: 26,
    color: '#FDB46C',
    abbrev: 'Eo',
  },
  {
    interval_no: 106,
    name: 'Priabonian',
    level: 'age',
    max_ma: 37.71,
    min_ma: 33.9,
    parent_no: 37,
    color: '#FDCDA1',
  },
  {
    interval_no: 107,
    name: 'Bartonian',
    level: 'age',
    max_ma: 41.03,
    min_ma: 37.71,
    parent_no: 37,
    color: '#FDC091',
  },
  {
    interval_no: 108,
    name: 'Lutetian',
    level: 'age',
    max_ma: 48.07,
    min_ma: 41.03,
    parent_no: 37,
    color: '#FCB482',
  },
  {
    interval_no: 109,
    name: 'Ypresian',
    level: 'age',
    max_ma: 56,
    min_ma: 48.07,
    parent_no: 37,
    color: '#FCA773',
  },
  {
    interval_no: 38,
    name: 'Paleocene',
    level: 'epoch',
    max_ma: 66,
    min_ma: 56,
    parent_no: 26,
    color: '#FDA75F',
    abbrev: 'Pal',
  },
  {
    interval_no: 110,
    name: 'Thanetian',
    level: 'age',
    max_ma: 59.24,
    min_ma: 56,
    parent_no: 38,
    color: '#FDBF6F',
  },
  {
    interval_no: 743,
    name: 'Selandian',
    level: 'age',
    max_ma: 61.66,
    min_ma: 59.24,
    parent_no: 38,
    color: '#FEBF65',
  },
  {
    interval_no: 111,
    name: 'Danian',
    level: 'age',
    max_ma: 66,
    min_ma: 61.66,
    parent_no: 38,
    color: '#FDB462',
  },
  {
    interval_no: 2,
    name: 'Mesozoic',
    level: 'era',
    max_ma: 251.902,
    min_ma: 66,
    parent_no: 751,
    color: '#67C5CA',
    abbrev: 'Mz',
  },
  {
    interval_no: 14,
    name: 'Cretaceous',
    level: 'period',
    max_ma: 143.1,
    min_ma: 66,
    parent_no: 2,
    color: '#7FC64E',
    abbrev: 'K',
  },
  {
    interval_no: 39,
    name: 'Late Cretaceous',
    level: 'epoch',
    max_ma: 100.5,
    min_ma: 66,
    parent_no: 14,
    color: '#A6D84A',
  },
  {
    interval_no: 112,
    name: 'Maastrichtian',
    level: 'age',
    max_ma: 72.2,
    min_ma: 66,
    parent_no: 39,
    color: '#F2FA8C',
  },
  {
    interval_no: 113,
    name: 'Campanian',
    level: 'age',
    max_ma: 83.6,
    min_ma: 72.2,
    parent_no: 39,
    color: '#E6F47F',
  },
  {
    interval_no: 114,
    name: 'Santonian',
    level: 'age',
    max_ma: 85.7,
    min_ma: 83.6,
    parent_no: 39,
    color: '#D9EF74',
  },
  {
    interval_no: 115,
    name: 'Coniacian',
    level: 'age',
    max_ma: 89.8,
    min_ma: 85.7,
    parent_no: 39,
    color: '#CCE968',
  },
  {
    interval_no: 116,
    name: 'Turonian',
    level: 'age',
    max_ma: 93.9,
    min_ma: 89.8,
    parent_no: 39,
    color: '#BFE35D',
  },
  {
    interval_no: 117,
    name: 'Cenomanian',
    level: 'age',
    max_ma: 100.5,
    min_ma: 93.9,
    parent_no: 39,
    color: '#B3DE53',
  },
  {
    interval_no: 40,
    name: 'Early Cretaceous',
    level: 'epoch',
    max_ma: 143.1,
    min_ma: 100.5,
    parent_no: 14,
    color: '#8CCD57',
  },
  {
    interval_no: 118,
    name: 'Albian',
    level: 'age',
    max_ma: 113.2,
    min_ma: 100.5,
    parent_no: 40,
    color: '#CCEA97',
  },
  {
    interval_no: 119,
    name: 'Aptian',
    level: 'age',
    max_ma: 121.4,
    min_ma: 113.2,
    parent_no: 40,
    color: '#BFE48A',
  },
  {
    interval_no: 120,
    name: 'Barremian',
    level: 'age',
    max_ma: 125.77,
    min_ma: 121.4,
    parent_no: 40,
    color: '#B3DF7F',
  },
  {
    interval_no: 121,
    name: 'Hauterivian',
    level: 'age',
    max_ma: 132.6,
    min_ma: 125.77,
    parent_no: 40,
    color: '#A6D975',
  },
  {
    interval_no: 122,
    name: 'Valanginian',
    level: 'age',
    max_ma: 137.05,
    min_ma: 132.6,
    parent_no: 40,
    color: '#99D36A',
  },
  {
    interval_no: 123,
    name: 'Berriasian',
    level: 'age',
    max_ma: 143.1,
    min_ma: 137.05,
    parent_no: 40,
    color: '#8CCD60',
  },
  {
    interval_no: 15,
    name: 'Jurassic',
    level: 'period',
    max_ma: 201.4,
    min_ma: 143.1,
    parent_no: 2,
    color: '#34B2C9',
    abbrev: 'J',
  },
  {
    interval_no: 41,
    name: 'Late Jurassic',
    level: 'epoch',
    max_ma: 161.5,
    min_ma: 143.1,
    parent_no: 15,
    color: '#B3E3EE',
  },
  {
    interval_no: 124,
    name: 'Tithonian',
    level: 'age',
    max_ma: 149.2,
    min_ma: 143.1,
    parent_no: 41,
    color: '#D9F1F7',
  },
  {
    interval_no: 125,
    name: 'Kimmeridgian',
    level: 'age',
    max_ma: 154.8,
    min_ma: 149.2,
    parent_no: 41,
    color: '#CCECF4',
  },
  {
    interval_no: 126,
    name: 'Oxfordian',
    level: 'age',
    max_ma: 161.5,
    min_ma: 154.8,
    parent_no: 41,
    color: '#BFE7F1',
  },
  {
    interval_no: 42,
    name: 'Middle Jurassic',
    level: 'epoch',
    max_ma: 174.7,
    min_ma: 161.5,
    parent_no: 15,
    color: '#80CFD8',
  },
  {
    interval_no: 127,
    name: 'Callovian',
    level: 'age',
    max_ma: 165.3,
    min_ma: 161.5,
    parent_no: 42,
    color: '#BFE7E5',
  },
  {
    interval_no: 128,
    name: 'Bathonian',
    level: 'age',
    max_ma: 168.2,
    min_ma: 165.3,
    parent_no: 42,
    color: '#B3E2E3',
  },
  {
    interval_no: 129,
    name: 'Bajocian',
    level: 'age',
    max_ma: 170.9,
    min_ma: 168.2,
    parent_no: 42,
    color: '#A6DDE0',
  },
  {
    interval_no: 130,
    name: 'Aalenian',
    level: 'age',
    max_ma: 174.7,
    min_ma: 170.9,
    parent_no: 42,
    color: '#9AD9DD',
  },
  {
    interval_no: 43,
    name: 'Early Jurassic',
    level: 'epoch',
    max_ma: 201.4,
    min_ma: 174.7,
    parent_no: 15,
    color: '#42AED0',
  },
  {
    interval_no: 131,
    name: 'Toarcian',
    level: 'age',
    max_ma: 184.2,
    min_ma: 174.7,
    parent_no: 43,
    color: '#99CEE3',
  },
  {
    interval_no: 132,
    name: 'Pliensbachian',
    level: 'age',
    max_ma: 192.9,
    min_ma: 184.2,
    parent_no: 43,
    color: '#80C5DD',
  },
  {
    interval_no: 133,
    name: 'Sinemurian',
    level: 'age',
    max_ma: 199.5,
    min_ma: 192.9,
    parent_no: 43,
    color: '#67BCD8',
  },
  {
    interval_no: 134,
    name: 'Hettangian',
    level: 'age',
    max_ma: 201.4,
    min_ma: 199.5,
    parent_no: 43,
    color: '#4EB3D3',
  },
  {
    interval_no: 16,
    name: 'Triassic',
    level: 'period',
    max_ma: 251.902,
    min_ma: 201.4,
    parent_no: 2,
    color: '#812B92',
    abbrev: 'Tr',
  },
  {
    interval_no: 44,
    name: 'Late Triassic',
    level: 'epoch',
    max_ma: 237,
    min_ma: 201.4,
    parent_no: 16,
    color: '#BD8CC3',
  },
  {
    interval_no: 135,
    name: 'Rhaetian',
    level: 'age',
    max_ma: 205.7,
    min_ma: 201.4,
    parent_no: 44,
    color: '#E3B9DB',
  },
  {
    interval_no: 136,
    name: 'Norian',
    level: 'age',
    max_ma: 227.3,
    min_ma: 205.7,
    parent_no: 44,
    color: '#D6AAD3',
  },
  {
    interval_no: 137,
    name: 'Carnian',
    level: 'age',
    max_ma: 237,
    min_ma: 227.3,
    parent_no: 44,
    color: '#C99BCB',
  },
  {
    interval_no: 45,
    name: 'Middle Triassic',
    level: 'epoch',
    max_ma: 246.7,
    min_ma: 237,
    parent_no: 16,
    color: '#B168B1',
  },
  {
    interval_no: 138,
    name: 'Ladinian',
    level: 'age',
    max_ma: 241.464,
    min_ma: 237,
    parent_no: 45,
    color: '#C983BF',
  },
  {
    interval_no: 139,
    name: 'Anisian',
    level: 'age',
    max_ma: 246.7,
    min_ma: 241.464,
    parent_no: 45,
    color: '#BC75B7',
  },
  {
    interval_no: 46,
    name: 'Early Triassic',
    level: 'epoch',
    max_ma: 251.902,
    min_ma: 246.7,
    parent_no: 16,
    color: '#983999',
  },
  {
    interval_no: 652,
    name: 'Olenekian',
    level: 'age',
    max_ma: 249.9,
    min_ma: 246.7,
    parent_no: 46,
    color: '#B051A5',
  },
  {
    interval_no: 653,
    name: 'Induan',
    level: 'age',
    max_ma: 251.902,
    min_ma: 249.9,
    parent_no: 46,
    color: '#A4469F',
  },
  {
    interval_no: 3,
    name: 'Paleozoic',
    level: 'era',
    max_ma: 538.8,
    min_ma: 251.902,
    parent_no: 751,
    color: '#99C08D',
    abbrev: 'Pz',
  },
  {
    interval_no: 17,
    name: 'Permian',
    level: 'period',
    max_ma: 298.9,
    min_ma: 251.902,
    parent_no: 3,
    color: '#F04028',
    abbrev: 'P',
  },
  {
    interval_no: 771,
    name: 'Lopingian',
    level: 'epoch',
    max_ma: 259.51,
    min_ma: 251.902,
    parent_no: 17,
    color: '#FBA794',
  },
  {
    interval_no: 715,
    name: 'Changhsingian',
    level: 'age',
    max_ma: 254.14,
    min_ma: 251.902,
    parent_no: 771,
    color: '#FCC0B2',
  },
  {
    interval_no: 716,
    name: 'Wuchiapingian',
    level: 'age',
    max_ma: 259.51,
    min_ma: 254.14,
    parent_no: 771,
    color: '#FCB4A2',
  },
  {
    interval_no: 772,
    name: 'Guadalupian',
    level: 'epoch',
    max_ma: 274.4,
    min_ma: 259.51,
    parent_no: 17,
    color: '#FB745C',
  },
  {
    interval_no: 145,
    name: 'Capitanian',
    level: 'age',
    max_ma: 264.28,
    min_ma: 259.51,
    parent_no: 772,
    color: '#FB9A85',
  },
  {
    interval_no: 146,
    name: 'Wordian',
    level: 'age',
    max_ma: 266.9,
    min_ma: 264.28,
    parent_no: 772,
    color: '#FB8D76',
  },
  {
    interval_no: 717,
    name: 'Roadian',
    level: 'age',
    max_ma: 274.4,
    min_ma: 266.9,
    parent_no: 772,
    color: '#FB8069',
  },
  {
    interval_no: 773,
    name: 'Cisuralian',
    level: 'epoch',
    max_ma: 298.9,
    min_ma: 274.4,
    parent_no: 17,
    color: '#EF5845',
  },
  {
    interval_no: 148,
    name: 'Kungurian',
    level: 'age',
    max_ma: 283.3,
    min_ma: 274.4,
    parent_no: 773,
    color: '#E38776',
  },
  {
    interval_no: 149,
    name: 'Artinskian',
    level: 'age',
    max_ma: 290.1,
    min_ma: 283.3,
    parent_no: 773,
    color: '#E37B68',
  },
  {
    interval_no: 150,
    name: 'Sakmarian',
    level: 'age',
    max_ma: 293.52,
    min_ma: 290.1,
    parent_no: 773,
    color: '#E36F5C',
  },
  {
    interval_no: 151,
    name: 'Asselian',
    level: 'age',
    max_ma: 298.9,
    min_ma: 293.52,
    parent_no: 773,
    color: '#E36350',
  },
  {
    interval_no: 18,
    name: 'Carboniferous',
    level: 'period',
    max_ma: 358.86,
    min_ma: 298.9,
    parent_no: 3,
    color: '#67A599',
    abbrev: 'C',
  },
  {
    interval_no: 27,
    name: 'Pennsylvanian',
    level: 'epoch',
    max_ma: 323.4,
    min_ma: 298.9,
    parent_no: 18,
    color: '#99C2B5',
  },
  {
    interval_no: 49,
    name: 'Gzhelian',
    level: 'age',
    max_ma: 303.7,
    min_ma: 298.9,
    parent_no: 27,
    color: '#CCD4C7',
  },
  {
    interval_no: 50,
    name: 'Kasimovian',
    level: 'age',
    max_ma: 307,
    min_ma: 303.7,
    parent_no: 27,
    color: '#BFD0C5',
  },
  {
    interval_no: 51,
    name: 'Moscovian',
    level: 'age',
    max_ma: 315.2,
    min_ma: 307,
    parent_no: 27,
    color: '#C7CBB9',
  },
  {
    interval_no: 52,
    name: 'Bashkirian',
    level: 'age',
    max_ma: 323.4,
    min_ma: 315.2,
    parent_no: 27,
    color: '#99C2B5',
  },
  {
    interval_no: 28,
    name: 'Mississippian',
    level: 'epoch',
    max_ma: 358.86,
    min_ma: 323.4,
    parent_no: 18,
    color: '#678F66',
  },
  {
    interval_no: 53,
    name: 'Serpukhovian',
    level: 'age',
    max_ma: 330.3,
    min_ma: 323.4,
    parent_no: 28,
    color: '#BFC26B',
  },
  {
    interval_no: 54,
    name: 'Visean',
    level: 'age',
    max_ma: 346.7,
    min_ma: 330.3,
    parent_no: 28,
    color: '#A6B96C',
  },
  {
    interval_no: 55,
    name: 'Tournaisian',
    level: 'age',
    max_ma: 358.86,
    min_ma: 346.7,
    parent_no: 28,
    color: '#8CB06C',
  },
  {
    interval_no: 19,
    name: 'Devonian',
    level: 'period',
    max_ma: 419.62,
    min_ma: 358.86,
    parent_no: 3,
    color: '#CB8C37',
    abbrev: 'D',
  },
  {
    interval_no: 56,
    name: 'Late Devonian',
    level: 'epoch',
    max_ma: 382.31,
    min_ma: 358.86,
    parent_no: 19,
    color: '#F1E19D',
  },
  {
    interval_no: 177,
    name: 'Famennian',
    level: 'age',
    max_ma: 372.15,
    min_ma: 358.86,
    parent_no: 56,
    color: '#F2EDC5',
  },
  {
    interval_no: 178,
    name: 'Frasnian',
    level: 'age',
    max_ma: 382.31,
    min_ma: 372.15,
    parent_no: 56,
    color: '#F2EDAD',
  },
  {
    interval_no: 57,
    name: 'Middle Devonian',
    level: 'epoch',
    max_ma: 393.47,
    min_ma: 382.31,
    parent_no: 19,
    color: '#F1C868',
  },
  {
    interval_no: 179,
    name: 'Givetian',
    level: 'age',
    max_ma: 387.95,
    min_ma: 382.31,
    parent_no: 57,
    color: '#F1E185',
  },
  {
    interval_no: 180,
    name: 'Eifelian',
    level: 'age',
    max_ma: 393.47,
    min_ma: 387.95,
    parent_no: 57,
    color: '#F1D576',
  },
  {
    interval_no: 58,
    name: 'Early Devonian',
    level: 'epoch',
    max_ma: 419.62,
    min_ma: 393.47,
    parent_no: 19,
    color: '#E5AC4D',
  },
  {
    interval_no: 181,
    name: 'Emsian',
    level: 'age',
    max_ma: 410.62,
    min_ma: 393.47,
    parent_no: 58,
    color: '#E5D075',
  },
  {
    interval_no: 182,
    name: 'Pragian',
    level: 'age',
    max_ma: 413.02,
    min_ma: 410.62,
    parent_no: 58,
    color: '#E5C468',
  },
  {
    interval_no: 183,
    name: 'Lochkovian',
    level: 'age',
    max_ma: 419.62,
    min_ma: 413.02,
    parent_no: 58,
    color: '#E5B75A',
  },
  {
    interval_no: 20,
    name: 'Silurian',
    level: 'period',
    max_ma: 443.1,
    min_ma: 419.62,
    parent_no: 3,
    color: '#B3E1B6',
    abbrev: 'S',
  },
  {
    interval_no: 59,
    name: 'Pridoli',
    level: 'epoch',
    max_ma: 422.7,
    min_ma: 419.62,
    parent_no: 20,
    color: '#E6F5E1',
  },
  {
    interval_no: 60,
    name: 'Ludlow',
    level: 'epoch',
    max_ma: 426.7,
    min_ma: 422.7,
    parent_no: 20,
    color: '#BFE6CF',
  },
  {
    interval_no: 184,
    name: 'Ludfordian',
    level: 'age',
    max_ma: 425,
    min_ma: 422.7,
    parent_no: 60,
    color: '#D9F0DF',
  },
  {
    interval_no: 185,
    name: 'Gorstian',
    level: 'age',
    max_ma: 426.7,
    min_ma: 425,
    parent_no: 60,
    color: '#CCECDD',
  },
  {
    interval_no: 61,
    name: 'Wenlock',
    level: 'epoch',
    max_ma: 432.9,
    min_ma: 426.7,
    parent_no: 20,
    color: '#B3E1C2',
  },
  {
    interval_no: 785,
    name: 'Homerian',
    level: 'age',
    max_ma: 430.6,
    min_ma: 426.7,
    parent_no: 61,
    color: '#CCEBD1',
  },
  {
    interval_no: 188,
    name: 'Sheinwoodian',
    level: 'age',
    max_ma: 432.9,
    min_ma: 430.6,
    parent_no: 61,
    color: '#BFE6C3',
  },
  {
    interval_no: 62,
    name: 'Llandovery',
    level: 'epoch',
    max_ma: 443.1,
    min_ma: 432.9,
    parent_no: 20,
    color: '#99D7B3',
  },
  {
    interval_no: 189,
    name: 'Telychian',
    level: 'age',
    max_ma: 438.6,
    min_ma: 432.9,
    parent_no: 62,
    color: '#BFE6CF',
  },
  {
    interval_no: 190,
    name: 'Aeronian',
    level: 'age',
    max_ma: 440.5,
    min_ma: 438.6,
    parent_no: 62,
    color: '#B3E1C2',
  },
  {
    interval_no: 191,
    name: 'Rhuddanian',
    level: 'age',
    max_ma: 443.1,
    min_ma: 440.5,
    parent_no: 62,
    color: '#A6DCB5',
  },
  {
    interval_no: 21,
    name: 'Ordovician',
    level: 'period',
    max_ma: 486.85,
    min_ma: 443.1,
    parent_no: 3,
    color: '#009270',
    abbrev: 'O',
  },
  {
    interval_no: 29,
    name: 'Late Ordovician',
    level: 'epoch',
    max_ma: 458.2,
    min_ma: 443.1,
    parent_no: 21,
    color: '#7FCA93',
  },
  {
    interval_no: 192,
    name: 'Hirnantian',
    level: 'age',
    max_ma: 445.2,
    min_ma: 443.1,
    parent_no: 29,
    color: '#A6DBAB',
  },
  {
    interval_no: 1008,
    name: 'Katian',
    level: 'age',
    max_ma: 452.8,
    min_ma: 445.2,
    parent_no: 29,
    color: '#99D69F',
  },
  {
    interval_no: 1009,
    name: 'Sandbian',
    level: 'age',
    max_ma: 458.2,
    min_ma: 452.8,
    parent_no: 29,
    color: '#8CD094',
  },
  {
    interval_no: 30,
    name: 'Middle Ordovician',
    level: 'epoch',
    max_ma: 471.3,
    min_ma: 458.2,
    parent_no: 21,
    color: '#4DB47E',
  },
  {
    interval_no: 556,
    name: 'Darriwilian',
    level: 'age',
    max_ma: 469.4,
    min_ma: 458.2,
    parent_no: 30,
    color: '#74C69C',
  },
  {
    interval_no: 1079,
    name: 'Dapingian',
    level: 'age',
    max_ma: 471.3,
    min_ma: 469.4,
    parent_no: 30,
    color: '#66C092',
  },
  {
    interval_no: 31,
    name: 'Early Ordovician',
    level: 'epoch',
    max_ma: 486.85,
    min_ma: 471.3,
    parent_no: 21,
    color: '#1A9D6F',
  },
  {
    interval_no: 1010,
    name: 'Floian',
    level: 'age',
    max_ma: 477.1,
    min_ma: 471.3,
    parent_no: 31,
    color: '#41B087',
  },
  {
    interval_no: 559,
    name: 'Tremadocian',
    level: 'age',
    max_ma: 486.85,
    min_ma: 477.1,
    parent_no: 31,
    color: '#33A97E',
  },
  {
    interval_no: 22,
    name: 'Cambrian',
    level: 'period',
    max_ma: 538.8,
    min_ma: 486.85,
    parent_no: 3,
    color: '#7FA056',
    abbrev: 'Cm',
  },
  {
    interval_no: 780,
    name: 'Furongian',
    level: 'epoch',
    max_ma: 497,
    min_ma: 486.85,
    parent_no: 22,
    color: '#B3E095',
  },
  {
    interval_no: 1112,
    name: 'Stage 10',
    level: 'age',
    max_ma: 491,
    min_ma: 486.85,
    parent_no: 780,
    color: '#E6F5C9',
  },
  {
    interval_no: 1113,
    name: 'Jiangshanian',
    level: 'age',
    max_ma: 494.2,
    min_ma: 491,
    parent_no: 780,
    color: '#D9F0BB',
  },
  {
    interval_no: 1086,
    name: 'Paibian',
    level: 'age',
    max_ma: 497,
    min_ma: 494.2,
    parent_no: 780,
    color: '#CCEBAE',
  },
  {
    interval_no: 1204,
    name: 'Miaolingian',
    level: 'epoch',
    max_ma: 506.5,
    min_ma: 497,
    parent_no: 22,
    color: '#A6CF86',
  },
  {
    interval_no: 1087,
    name: 'Guzhangian',
    level: 'age',
    max_ma: 500.5,
    min_ma: 497,
    parent_no: 1204,
    color: '#CCDFAA',
  },
  {
    interval_no: 1116,
    name: 'Drumian',
    level: 'age',
    max_ma: 504.5,
    min_ma: 500.5,
    parent_no: 1204,
    color: '#BFD99D',
  },
  {
    interval_no: 1205,
    name: 'Wuliuan',
    level: 'age',
    max_ma: 506.5,
    min_ma: 504.5,
    parent_no: 1204,
    color: '#B3D492',
  },
  {
    interval_no: 1110,
    name: 'Series 2',
    level: 'epoch',
    max_ma: 521,
    min_ma: 506.5,
    parent_no: 22,
    color: '#99C078',
  },
  {
    interval_no: 1118,
    name: 'Stage 4',
    level: 'age',
    max_ma: 514.5,
    min_ma: 506.5,
    parent_no: 1110,
    color: '#B3CA8E',
  },
  {
    interval_no: 1119,
    name: 'Stage 3',
    level: 'age',
    max_ma: 521,
    min_ma: 514.5,
    parent_no: 1110,
    color: '#A6C583',
  },
  {
    interval_no: 1111,
    name: 'Terreneuvian',
    level: 'epoch',
    max_ma: 538.8,
    min_ma: 521,
    parent_no: 22,
    color: '#8CB06C',
  },
  {
    interval_no: 1120,
    name: 'Stage 2',
    level: 'age',
    max_ma: 529,
    min_ma: 521,
    parent_no: 1111,
    color: '#A6BA80',
  },
  {
    interval_no: 1121,
    name: 'Fortunian',
    level: 'age',
    max_ma: 538.8,
    min_ma: 529,
    parent_no: 1111,
    color: '#99B575',
  },
  {
    interval_no: 752,
    name: 'Proterozoic',
    level: 'eon',
    max_ma: 2500,
    min_ma: 538.8,
    color: '#F73563',
    abbrev: 'Ptz',
  },
  {
    interval_no: 754,
    name: 'Neoproterozoic',
    level: 'era',
    max_ma: 1000,
    min_ma: 538.8,
    parent_no: 752,
    color: '#FEB342',
    abbrev: 'Nptz',
  },
  {
    interval_no: 761,
    name: 'Ediacaran',
    level: 'period',
    max_ma: 635,
    min_ma: 538.8,
    parent_no: 754,
    color: '#FED96A',
    abbrev: 'E',
  },
  {
    interval_no: 762,
    name: 'Cryogenian',
    level: 'period',
    max_ma: 720,
    min_ma: 635,
    parent_no: 754,
    color: '#FECC5C',
    abbrev: 'Cr',
  },
  {
    interval_no: 763,
    name: 'Tonian',
    level: 'period',
    max_ma: 1000,
    min_ma: 720,
    parent_no: 754,
    color: '#FEBF4E',
    abbrev: 'T',
  },
  {
    interval_no: 755,
    name: 'Mesoproterozoic',
    level: 'era',
    max_ma: 1600,
    min_ma: 1000,
    parent_no: 752,
    color: '#FDB462',
    abbrev: 'Mptz',
  },
  {
    interval_no: 764,
    name: 'Stenian',
    level: 'period',
    max_ma: 1200,
    min_ma: 1000,
    parent_no: 755,
    color: '#FED99A',
    abbrev: 'St',
  },
  {
    interval_no: 765,
    name: 'Ectasian',
    level: 'period',
    max_ma: 1400,
    min_ma: 1200,
    parent_no: 755,
    color: '#F3CC8A',
    abbrev: 'Ec',
  },
  {
    interval_no: 766,
    name: 'Calymmian',
    level: 'period',
    max_ma: 1600,
    min_ma: 1400,
    parent_no: 755,
    color: '#FDC07A',
    abbrev: 'Ca',
  },
  {
    interval_no: 756,
    name: 'Paleoproterozoic',
    level: 'era',
    max_ma: 2500,
    min_ma: 1600,
    parent_no: 752,
    color: '#F74370',
    abbrev: 'Pptz',
  },
  {
    interval_no: 767,
    name: 'Statherian',
    level: 'period',
    max_ma: 1800,
    min_ma: 1600,
    parent_no: 756,
    color: '#F875A7',
    abbrev: 'St',
  },
  {
    interval_no: 768,
    name: 'Orosirian',
    level: 'period',
    max_ma: 2050,
    min_ma: 1800,
    parent_no: 756,
    color: '#F76898',
    abbrev: 'Or',
  },
  {
    interval_no: 769,
    name: 'Rhyacian',
    level: 'period',
    max_ma: 2300,
    min_ma: 2050,
    parent_no: 756,
    color: '#F75B89',
    abbrev: 'R',
  },
  {
    interval_no: 770,
    name: 'Siderian',
    level: 'period',
    max_ma: 2500,
    min_ma: 2300,
    parent_no: 756,
    color: '#F74F7C',
    abbrev: 'Sd',
  },
  {
    interval_no: 753,
    name: 'Archean',
    level: 'eon',
    max_ma: 4031,
    min_ma: 2500,
    color: '#F0047F',
    abbrev: 'Arc',
  },
  {
    interval_no: 757,
    name: 'Neoarchean',
    level: 'era',
    max_ma: 2800,
    min_ma: 2500,
    parent_no: 753,
    color: '#F99BC1',
    abbrev: 'Narc',
  },
  {
    interval_no: 758,
    name: 'Mesoarchean',
    level: 'era',
    max_ma: 3200,
    min_ma: 2800,
    parent_no: 753,
    color: '#F768A9',
    abbrev: 'Marc',
  },
  {
    interval_no: 759,
    name: 'Paleoarchean',
    level: 'era',
    max_ma: 3600,
    min_ma: 3200,
    parent_no: 753,
    color: '#F444A9',
    abbrev: 'Parc',
  },
  {
    interval_no: 760,
    name: 'Eoarchean',
    level: 'era',
    max_ma: 4031,
    min_ma: 3600,
    parent_no: 753,
    color: '#DA037F',
    abbrev: 'Earc',
  },
  {
    interval_no: 11,
    name: 'Hadean',
    level: 'eon',
    max_ma: 4567,
    min_ma: 4031,
    color: '#A83A94',
  },
];
